title: "SBD Revúca"
description: "Stavebné bytové družstvo Revúca"
theme: minima
markdown: kramdown
collections:
  posts:
    output: true

# Pagination v2
pagination:
  enabled: true
  per_page: 5
  permalink: '/strana:num/'
  title: ':title - strana :num'
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-paginate-v2
