title: "SBD Revúca"
description: "Stavebné bytové družstvo Revúca"
theme: minima
markdown: kramdown
collections:
  posts:
    output: true
paginate: 5
paginate_path: "/oznamy/strana:num"
plugins:
  - jekyll-paginate
